# Generated by Django 4.2.7 on 2026-09-14 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='社团名称')),
                ('description', models.TextField(verbose_name='社团信息')),
                ('category', models.CharField(max_length=50, verbose_name='社团类型')),
                ('founded_date', models.DateField(verbose_name='成立日期')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='活动地点')),
            ],
            options={
                'verbose_name': '社团',
                'verbose_name_plural': '社团',
            },
        ),
        migrations.CreateModel(
            name='ClubAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=50, verbose_name='管理员姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='clubs.club', verbose_name='所属社团')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='后台账号')),
            ],
            options={
                'verbose_name': '社团管理员',
                'verbose_name_plural': '社团管理员',
            },
        ),
    ]
